// src/pages/analyzer/AIAnalysisReport.jsx
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import {
  FaCheckCircle, FaTimesCircle, FaExclamationCircle, FaChartBar, FaLightbulb,
  FaAward, FaUsers, FaGraduationCap, FaCode, FaTrophy, FaArrowUp, FaDownload,
  FaArrowLeft, FaShareAlt, FaPrint, FaStar, FaRegStar, FaClock, FaFilePdf
} from 'react-icons/fa';
import toast from 'react-hot-toast';

const AIAnalysisReport = ({ analysis, onBack }) => {
  const [expandedSection, setExpandedSection] = useState('overview');

  if (!analysis || !analysis.analysis) {
    return (
      <div className="text-center py-16 bg-white rounded-2xl shadow-xl">
        <FaExclamationCircle className="text-6xl text-yellow-500 mx-auto mb-4" />
        <h3 className="text-2xl font-bold text-gray-900 mb-2">No Analysis Data</h3>
        <p className="text-gray-700 mb-6">Unable to load analysis results</p>
        <button
          onClick={onBack}
          className="px-6 py-3 bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition"
        >
          <FaArrowLeft className="inline mr-2" /> Back to Analyzer
        </button>
      </div>
    );
  }

  const { analysis: reportData, title, jobTitle, timestamp, overallScore } = analysis;

  const downloadReport = () => {
    try {
      const reportContent = `
AI RESUME ANALYSIS REPORT
========================

Report Title: ${title || 'Analysis Report'}
Date: ${timestamp ? new Date(timestamp).toLocaleString() : new Date().toLocaleString()}
Job Title: ${jobTitle || 'Not Specified'}

OVERALL SCORE: ${overallScore || reportData?.jobFitScore?.overallScore || 0}%

===== SKILLS ANALYSIS =====
${reportData?.skillsMatch ? `
Match Percentage: ${reportData.skillsMatch.matchPercentage || 0}%

Your Skills:
${(reportData.skillsMatch.resumeSkills || []).map(s => `- ${s}`).join('\n')}

Job Required Skills:
${(reportData.skillsMatch.jobSkills || []).map(s => `- ${s}`).join('\n')}

Matched Skills:
${(reportData.skillsMatch.matchedSkills || []).map(s => `- ✓ ${s}`).join('\n')}

Missing Skills:
${(reportData.skillsMatch.missingSkills || []).map(s => `- ✗ ${s}`).join('\n')}
` : 'No skills data available'}

===== EXPERIENCE ANALYSIS =====
${reportData?.experienceAnalysis ? `
Total Experience: ${reportData.experienceAnalysis.totalYears || 0} years
Positions: ${reportData.experienceAnalysis.experienceCount || 0}

Summary: ${reportData.experienceAnalysis.summary || 'No summary available'}

Roles:
${(reportData.experienceAnalysis.roles || []).map(r => `- ${r.title || 'Untitled'} at ${r.company || 'Unknown'} (${r.duration || 'N/A'})`).join('\n')}
` : 'No experience data available'}

===== ATS COMPATIBILITY =====
${reportData?.atsScore ? `
Score: ${reportData.atsScore.score || 0}/${reportData.atsScore.maxScore || 100}
Level: ${reportData.atsScore.level || 'Not Rated'}

Factors:
${(reportData.atsScore.factors || []).map(f => `- ${f}`).join('\n')}
` : 'No ATS data available'}

===== RECOMMENDED IMPROVEMENTS =====
${(reportData?.improvements || []).map(imp => `
Priority: ${imp.priority?.toUpperCase() || 'MEDIUM'}
Category: ${imp.category || 'General'}
Suggestion: ${imp.suggestion || 'No suggestion provided'}
Impact: ${imp.impact || 'Medium impact'}
`).join('\n')}

===== JOB FIT CRITERIA =====
${(reportData?.jobFitScore?.criteria || []).map(c => `
${c.met ? '✓' : '✗'} ${c.name || 'Unnamed'}: ${c.value || 'N/A'}
`).join('\n')}

Generated by AI Resume Analyzer
`;

      const element = document.createElement('a');
      element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(reportContent));
      element.setAttribute('download', `analysis_${new Date().getTime()}.txt`);
      element.style.display = 'none';
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);

      toast.success('Report downloaded successfully!');
    } catch (error) {
      console.error('Download error:', error);
      toast.error('Failed to download report');
    }
  };

  const shareReport = () => {
    if (navigator.share) {
      navigator.share({
        title: 'AI Resume Analysis Report',
        text: `Check out my resume analysis! Score: ${overallScore || reportData?.jobFitScore?.overallScore || 0}%`,
        url: window.location.href,
      }).catch(() => {
        toast.error('Share cancelled');
      });
    } else {
      navigator.clipboard.writeText(window.location.href);
      toast.success('Link copied to clipboard!');
    }
  };

  const printReport = () => {
    window.print();
  };

  const getScoreColor = (score) => {
    if (score >= 80) return 'text-green-600';
    if (score >= 60) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getScoreBg = (score) => {
    if (score >= 80) return 'bg-green-100';
    if (score >= 60) return 'bg-yellow-100';
    return 'bg-red-100';
  };

  return (
    <div className="space-y-6">
      {/* Header with Actions */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 rounded-2xl p-8 text-white shadow-xl"
      >
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <button
              onClick={onBack}
              className="p-3 hover:bg-white/20 rounded-xl transition-all"
            >
              <FaArrowLeft className="text-xl" />
            </button>
            <div>
              <h2 className="text-3xl font-bold mb-2 text-white">{title || 'Analysis Report'}</h2>
              <p className="text-blue-100 flex items-center gap-2">
                <FaClock /> {timestamp ? new Date(timestamp).toLocaleString() : new Date().toLocaleString()}
              </p>
            </div>
          </div>
          <div className="flex gap-3">
            <button
              onClick={shareReport}
              className="p-3 bg-white/10 hover:bg-white/20 rounded-xl transition-all text-white"
              title="Share Report"
            >
              <FaShareAlt />
            </button>
            <button
              onClick={printReport}
              className="p-3 bg-white/10 hover:bg-white/20 rounded-xl transition-all text-white"
              title="Print Report"
            >
              <FaPrint />
            </button>
            <button
              onClick={downloadReport}
              className="px-6 py-3 bg-white text-blue-600 rounded-xl hover:bg-blue-50 transition-all font-semibold flex items-center gap-2"
            >
              <FaDownload /> Download
            </button>
          </div>
        </div>
      </motion.div>

      {/* Overall Score Card */}
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        className="bg-white rounded-2xl border border-gray-200 p-8 shadow-lg"
      >
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
          <div className="text-center">
            <div className={`text-6xl font-bold ${getScoreColor(overallScore || reportData?.jobFitScore?.overallScore || 0)} mb-2`}>
              {overallScore || reportData?.jobFitScore?.overallScore || 0}
            </div>
            <div className="text-gray-800 font-semibold">Job Fit Score</div>
            <div className="text-sm text-gray-600 mt-2">
              {reportData?.jobFitScore?.recommendation || 'Analyzed'}
            </div>
          </div>

          <div className="text-center">
            <div className={`text-6xl font-bold ${getScoreColor(reportData?.skillsMatch?.matchPercentage || 0)} mb-2`}>
              {reportData?.skillsMatch?.matchPercentage || 0}%
            </div>
            <div className="text-gray-800 font-semibold">Skills Match</div>
            <div className="text-sm text-gray-600 mt-2">
              {reportData?.skillsMatch?.matchedSkills?.length || 0}/{reportData?.skillsMatch?.jobSkills?.length || 0} skills
            </div>
          </div>

          <div className="text-center">
            <div className={`text-6xl font-bold ${getScoreColor((reportData?.atsScore?.score / reportData?.atsScore?.maxScore) * 100 || 0)} mb-2`}>
              {reportData?.atsScore?.score || 0}
            </div>
            <div className="text-gray-800 font-semibold">ATS Score</div>
            <div className="text-sm text-gray-600 mt-2">
              {reportData?.atsScore?.level || 'N/A'}
            </div>
          </div>

          <div className="text-center">
            <div className="text-6xl font-bold text-purple-600 mb-2">
              {reportData?.experienceAnalysis?.totalYears || 0}
            </div>
            <div className="text-gray-800 font-semibold">Years Exp.</div>
            <div className="text-sm text-gray-600 mt-2">
              {reportData?.experienceAnalysis?.experienceCount || 0} positions
            </div>
          </div>
        </div>
      </motion.div>

      {/* Skills Analysis */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="bg-white rounded-2xl border border-gray-200 p-8 shadow-lg"
      >
        <h3 className="text-2xl font-bold mb-6 flex items-center gap-3 text-gray-900">
          <FaCode className="text-blue-600" /> Skills Analysis
        </h3>

        <div className="grid md:grid-cols-2 gap-8">
          <div>
            <h4 className="font-semibold text-gray-800 mb-4 flex items-center gap-2">
              <FaCheckCircle className="text-green-500" /> Your Skills
            </h4>
            <div className="flex flex-wrap gap-2">
              {(reportData?.skillsMatch?.resumeSkills || []).map((skill, idx) => (
                <span
                  key={idx}
                  className="bg-blue-100 text-blue-800 px-3 py-1.5 rounded-lg text-sm font-medium"
                >
                  {skill}
                </span>
              ))}
            </div>
          </div>

          <div>
            <h4 className="font-semibold text-gray-800 mb-4 flex items-center gap-2">
              <FaExclamationCircle className="text-purple-500" /> Job Requirements
            </h4>
            <div className="flex flex-wrap gap-2">
              {(reportData?.skillsMatch?.jobSkills || []).map((skill, idx) => (
                <span
                  key={idx}
                  className="bg-purple-100 text-purple-800 px-3 py-1.5 rounded-lg text-sm font-medium"
                >
                  {skill}
                </span>
              ))}
            </div>
          </div>

          <div className="md:col-span-2">
            <h4 className="font-semibold text-gray-800 mb-4 text-green-600 flex items-center gap-2">
              <FaCheckCircle /> Matched Skills
            </h4>
            <div className="flex flex-wrap gap-2">
              {(reportData?.skillsMatch?.matchedSkills || []).map((skill, idx) => (
                <span
                  key={idx}
                  className="bg-green-100 text-green-800 px-3 py-1.5 rounded-lg text-sm font-medium"
                >
                  ✓ {skill}
                </span>
              ))}
            </div>
          </div>

          {(reportData?.skillsMatch?.missingSkills || []).length > 0 && (
            <div className="md:col-span-2">
              <h4 className="font-semibold text-gray-800 mb-4 text-red-600 flex items-center gap-2">
                <FaTimesCircle /> Missing Skills to Add
              </h4>
              <div className="flex flex-wrap gap-2">
                {(reportData?.skillsMatch?.missingSkills || []).map((skill, idx) => (
                  <span
                    key={idx}
                    className="bg-red-100 text-red-800 px-3 py-1.5 rounded-lg text-sm font-medium"
                  >
                    {skill}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      </motion.div>

      {/* Experience Analysis */}
      {reportData?.experienceAnalysis && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="bg-white rounded-2xl border border-gray-200 p-8 shadow-lg"
        >
          <h3 className="text-2xl font-bold mb-6 flex items-center gap-3 text-gray-900">
            <FaTrophy className="text-orange-500" /> Experience Summary
          </h3>

          <div className="grid md:grid-cols-3 gap-6 mb-8">
            <div className="bg-gradient-to-br from-orange-50 to-yellow-50 rounded-xl p-6 text-center">
              <div className="text-4xl font-bold text-orange-600 mb-2">
                {reportData.experienceAnalysis.totalYears}+
              </div>
              <div className="text-gray-800 font-semibold">Years of Experience</div>
            </div>

            <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-xl p-6 text-center">
              <div className="text-4xl font-bold text-blue-600 mb-2">
                {reportData.experienceAnalysis.experienceCount}
              </div>
              <div className="text-gray-800 font-semibold">Positions Held</div>
            </div>

            <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-xl p-6 text-center">
              <div className="text-4xl font-bold text-purple-600 mb-2">
                {reportData.experienceAnalysis.roles?.length || 0}
              </div>
              <div className="text-gray-800 font-semibold">Roles Analyzed</div>
            </div>
          </div>

          {reportData.experienceAnalysis.summary && (
            <div className="mb-6 p-4 bg-gray-50 rounded-xl">
              <p className="text-gray-800 italic">"{reportData.experienceAnalysis.summary}"</p>
            </div>
          )}

          <div>
            <h4 className="font-semibold text-gray-800 mb-4">Work History</h4>
            <div className="space-y-4">
              {(reportData.experienceAnalysis.roles || []).map((role, idx) => (
                <div key={idx} className="border-l-4 border-blue-500 pl-4 py-2">
                  <div className="font-bold text-gray-900">{role.title || 'Untitled'}</div>
                  <div className="text-gray-800">{role.company || 'Unknown Company'}</div>
                  <div className="text-sm text-gray-600">{role.duration || 'Duration N/A'}</div>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      )}

      {/* ATS Analysis */}
      {reportData?.atsScore && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="bg-white rounded-2xl border border-gray-200 p-8 shadow-lg"
        >
          <h3 className="text-2xl font-bold mb-6 flex items-center gap-3 text-gray-900">
            <FaChartBar className="text-purple-600" /> ATS Compatibility
          </h3>

          <div className="mb-6">
            <div className="flex items-center justify-between mb-2">
              <span className="font-semibold text-gray-800">ATS Score</span>
              <span className={`text-3xl font-bold ${getScoreColor((reportData.atsScore.score / reportData.atsScore.maxScore) * 100)}`}>
                {reportData.atsScore.score}/{reportData.atsScore.maxScore}
              </span>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-4">
              <div
                className={`h-4 rounded-full transition-all ${getScoreBg((reportData.atsScore.score / reportData.atsScore.maxScore) * 100)}`}
                style={{ width: `${(reportData.atsScore.score / reportData.atsScore.maxScore) * 100}%` }}
              />
            </div>
            <div className={`text-sm mt-2 font-medium ${getScoreColor((reportData.atsScore.score / reportData.atsScore.maxScore) * 100)}`}>
              {reportData.atsScore.level}
            </div>
          </div>

          <div className="space-y-3">
            <h4 className="font-semibold text-gray-800 mb-3">Positive Factors:</h4>
            {(reportData.atsScore.factors || []).map((factor, idx) => (
              <div key={idx} className="flex items-start gap-3 p-3 bg-green-50 rounded-xl">
                <FaCheckCircle className="text-green-500 mt-1 flex-shrink-0" />
                <span className="text-gray-800">{factor}</span>
              </div>
            ))}
          </div>
        </motion.div>
      )}

      {/* Improvements */}
      {(reportData?.improvements || []).length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="bg-white rounded-2xl border border-gray-200 p-8 shadow-lg"
        >
          <h3 className="text-2xl font-bold mb-6 flex items-center gap-3 text-gray-900">
            <FaLightbulb className="text-yellow-500" /> Recommended Improvements
          </h3>

          <div className="space-y-4">
            {(reportData.improvements || []).map((improvement, idx) => (
              <div
                key={idx}
                className={`border-l-4 p-5 rounded-xl ${improvement.priority === 'critical'
                  ? 'border-red-500 bg-red-50'
                  : improvement.priority === 'high'
                    ? 'border-orange-500 bg-orange-50'
                    : 'border-yellow-500 bg-yellow-50'
                  }`}
              >
                <div className="flex items-start justify-between mb-3">
                  <div className="font-bold text-gray-900 text-lg">{improvement.category || 'General'}</div>
                  <span
                    className={`text-xs font-bold px-3 py-1.5 rounded-full ${improvement.priority === 'critical'
                      ? 'bg-red-200 text-red-800'
                      : improvement.priority === 'high'
                        ? 'bg-orange-200 text-orange-800'
                        : 'bg-yellow-200 text-yellow-800'
                      }`}
                  >
                    {improvement.priority?.toUpperCase() || 'MEDIUM'}
                  </span>
                </div>
                <p className="text-gray-800 mb-3">{improvement.suggestion || 'No suggestion provided'}</p>
                <div className="text-sm text-gray-700 flex items-center gap-2">
                  <FaArrowUp className="text-green-500" />
                  {improvement.impact || 'Medium impact on your resume'}
                </div>
              </div>
            ))}
          </div>
        </motion.div>
      )}

      {/* Job Fit Criteria */}
      {(reportData?.jobFitScore?.criteria || []).length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
          className="bg-white rounded-2xl border border-gray-200 p-8 shadow-lg"
        >
          <h3 className="text-2xl font-bold mb-6 flex items-center gap-3 text-gray-900">
            <FaAward className="text-blue-600" /> Job Fit Criteria
          </h3>

          <div className="space-y-3">
            {(reportData.jobFitScore.criteria || []).map((criterion, idx) => (
              <div
                key={idx}
                className={`flex items-center gap-4 p-4 rounded-xl ${criterion.met
                  ? 'bg-green-50 border border-green-200'
                  : 'bg-gray-50 border border-gray-200'
                  }`}
              >
                {criterion.met ? (
                  <FaCheckCircle className="text-green-600 text-xl flex-shrink-0" />
                ) : (
                  <FaTimesCircle className="text-gray-500 text-xl flex-shrink-0" />
                )}
                <div className="flex-1">
                  <div className="font-bold text-gray-900">{criterion.name || 'Unnamed Criterion'}</div>
                  <div className={criterion.met ? 'text-green-700' : 'text-gray-700'}>
                    {criterion.value || 'No value provided'}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </motion.div>
      )}

      {/* Job Description Preview */}
      {analysis.jobDescription && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6 }}
          className="bg-white rounded-2xl border border-gray-200 p-8 shadow-lg"
        >
          <h3 className="text-2xl font-bold mb-4 flex items-center gap-3 text-gray-900">
            <FaFilePdf className="text-red-500" /> Job Description Analyzed
          </h3>
          <div className="bg-gray-50 p-4 rounded-xl max-h-60 overflow-y-auto">
            <p className="text-gray-800 whitespace-pre-wrap">{analysis.jobDescription}</p>
          </div>
        </motion.div>
      )}
    </div>
  );
};

export default React.memo(AIAnalysisReport);